title: Hac's note
description: Place where i store most of my notes 

theme: jekyll-theme-hacker

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
